name: CI

on:
  push:
    branches:
      - master
      - branch-composite-action
    tags:
      - '*'
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Ubuntu
        run: sudo apt-get install language-pack-en language-pack-de

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade --force --no-cache-dir pip
          pip install --force --no-cache-dir -r requirements.txt
          pip install --force --no-cache-dir pytest mock

      - name: PyTest
        env:
          PYTHONPATH: ..
        run: |
          cd test
          python -m pytest --continue-on-collection-errors --junit-xml ../test-results/pytest.xml

      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        # the action is useless on pull_request events from fork repositories
        # as it can not create check runs or pull request comments
        if: >
          ( success() || failure() ) &&
          ( github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository )
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "test-results/*.xml"
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
          log_level: DEBUG

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: |
            test-results/*.xml
            unit-test-results.json
